# Generated by Django 3.0.2 on 2021-03-30 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0002_auto_20210329_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('tempo', models.CharField(max_length=5)),
                ('link', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='musicas', to='album.Album')),
            ],
            options={
                'db_table': 'musica',
                'ordering': ('num',),
            },
        ),
    ]
