# Generated by Django 3.0.2 on 2021-03-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=70, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=70)),
            ],
            options={
                'db_table': 'artista',
                'ordering': ('nome',),
            },
        ),
    ]
