# Generated by Django 3.0.2 on 2021-03-30 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=70, unique=True)),
                ('capa', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artista.Artista')),
            ],
            options={
                'db_table': 'album',
                'ordering': ('nome',),
            },
        ),
    ]
