# Generated by Django 3.0.2 on 2021-03-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='albuns', to='artista.Artista'),
        ),
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.CharField(max_length=150),
        ),
    ]
